name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: moa_db
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: "adopt"

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Start MySQL Service
        run: |
          docker run -d --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=moa_db mysql:8
          sleep 10

      - name: Check MySQL Container Status
        run: docker inspect --format '{{.State.Status}}' mysql

      - name: Check IP
        run: docker inspect --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mysql

      - name: Install jq
        run: |
          apt-get update
          apt-get install -y jq

      - name: Check MySQL Connection
        run: |
          MYSQL_PORT=$(docker inspect --format='{{(index (index .NetworkSettings.Ports "3306") 0).HostPort}}' mysql)
          echo "MySQL Container Port: $MYSQL_PORT"
          nc -zv 172.17.0.2 $MYSQL_PORT

      - name: Print MySQL Logs
        run: docker logs mysql

      - name: Make gradlew script executable
        run: cd backend && chmod +x gradlew

      - name: Run Unit Tests
        run: cd backend && ./gradlew test
