name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: "adopt"

      - name: Setup H2 database
        uses: docker://oarmstrong/h2
        with:
          args: -e H2_OPTIONS='-ifNotExists -tcp -tcpAllowOthers -tcpPort 9092'

      - name: Make gradlew script executable
        run: cd backend && chmod +x gradlew

      - name: Run Unit Tests
        run: cd backend && ./gradlew test
