name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: "adopt"

      - name: Configure Test Database
        run: |
          echo "spring.datasource.url = jdbc:mysql://test-db-host:3306/test_database" > backend/src/test/resources/application-test.properties
          echo "spring.datasource.username = test-username" >> backend/src/test/resources/application-test.properties
          echo "spring.datasource.password = test-password" >> backend/src/test/resources/application-test.properties

      - name: Make gradlew script executable
        run: cd backend && chmod +x gradlew

      - name: Run Unit Tests
        run: cd backend && ./gradlew test
